=== FenixEdu/fenixedu-academic/metadata/fenix-renderers-schemas.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
  The root element 'schemas' allows the definition of several schemas. 
  -->
<!ELEMENT schemas (schema*)>

<!--
  Each schema must have an unique name and at least one slot specified.
  
  The 'type' attribute specifies to which object type this schema is to be
  applied. This information is used to verify is the specified slots exist
  in the object and if there is a way of rendering each slot.
  
  NOTE: 'type' currently is not used nor are the schemas verified as said
  TODO: implement the verification if slots exist in the defined schemas.
-->
<!ELEMENT schema (slot+)>

<!ATTLIST schema
	type NMTOKEN #REQUIRED
	name ID #REQUIRED
>

<!--
  The 'slot' element indicates that the slot with the specified name should be
  rendered when using this schema.
  
  Additionaly you can specify the layout used when rendering the slot value and
  even the schema that will be used.

  You can also specify the schema used to present the slot value.
  
  When rendering the slot label a convention is used to automatically find a valid
  entry in the render resources. Nevertheless you can specify, with the 'key' attribute,
  the exact key that will be used.
  
  The acommodate cases were you need to receive input for the slot, a validator can
  be specified. The validator is the name of the class that will be instantiated to
  validate the input value.
  
  If no value is associated with the slot, a default value can be given. The value is
  converted from the given string to the type of the slot.
-->
<!ELEMENT slot (property*)>

<!ATTLIST slot
	name CDATA #REQUIRED
	layout NMTOKEN #IMPLIED
	schema IDREF #IMPLIED
	key NMTOKEN #IMPLIED
	validator NMTOKEN #IMPLIED
	default CDATA #IMPLIED
>

<!--
  The 'property' element allows the configuration of the renderer used to present
  each slot value. Remember that the coosen renderer can be different every time
  so it is the renderer's responsability to undestand the properties passed.
  -->
<!ELEMENT property EMPTY>

<!ATTLIST property
	value NMTOKEN #REQUIRED
	name NMTOKEN #REQUIRED
>

=== FenixEdu/fenixedu-academic/fenixedu-quc/src/main/webapp/WEB-INF/fenixedu-quc/schemas-config.xml
<!--

    Copyright © 2002 Instituto Superior Técnico

    This file is part of FenixEdu Core.

    FenixEdu Core is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FenixEdu Core is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with FenixEdu Core.  If not, see <http://www.gnu.org/licenses/>.

-->

<!DOCTYPE schemas SYSTEM "../fenix-renderers-schemas.dtd">

<schemas>
<schema name="org.fenixedu.academic.domain.inquiry.SelectInquiryResponsePeriod.edit"
		type="org.fenixedu.academic.dto.inquiries.InquiryDefinitionPeriodBean" bundle="INQUIRIES_RESOURCES">
	<slot name="responsePeriodType" layout="menu-select-postback">
		<property name="providerClass"	value="org.fenixedu.academic.ui.renderers.providers.choiceType.replacement.single.InquiryResponsePeriodTypeProvider" />
		<property name="nullOptionHidden" value="true"/>
		<property name="destination" value="postBack"/>
	</slot>
	<slot name="executionPeriod" layout="menu-select-postback">
		<property name="providerClass" value="org.fenixedu.academic.ui.renderers.providers.ExecutionPeriodsReverseOrderProvider" />
		<property name="nullOptionHidden" value="true"/>
		<property name="format" value="${semester}º Semestre ${executionYear.year}" />
		<property name="destination" value="postBack"/>
	</slot>
</schema>

<schema name="org.fenixedu.academic.domain.inquiry.InquiryResponsePeriodMessage.edit"
		type="org.fenixedu.academic.dto.inquiries.InquiryDefinitionPeriodBean" bundle="INQUIRIES_RESOURCES">
	<slot name="begin"/>
	<slot name="end"/>
	<slot name="message" layout="rich-text">
   		<property name="safe" value="true" />
   		<property name="columns" value="100"/>
   		<property name="rows" value="30"/>
   		<property name="config" value="advanced" />
	</slot>
</schema>
	
<schema name="inquiryQuestionDTO.answer"
		type="org.fenixedu.academic.dto.inquiries.InquiryQuestionDTO" >	
	<slot name="responseValue" />
</schema>

<schema name="questionResultsSummaryBean.input"
		type="org.fenixedu.academic.dto.inquiries.QuestionResultsSummaryBean" >
	<slot name="editableComment">
	</slot>
</schema>

<schema name="inquiriesStudentExecutionPeriod.submitWeeklySpentHours"
		type="org.fenixedu.academic.dto.VariantBean" bundle="INQUIRIES_RESOURCES">
	<slot name="integer" >
		<property name="size" value="5" />
		<property name="maxLength" value="3" />	
		<validator class="pt.ist.fenixWebFramework.renderers.validators.RequiredValidator"/>
		<validator class="pt.ist.fenixWebFramework.renderers.validators.NumberValidator"/>
        <validator class="org.fenixedu.academic.ui.renderers.validators.NumberRangeValidator">
            <property name="lowerBound" value="0"/>
            <property name="upperBound" value="168"/>
        </validator>		
	</slot>
</schema>

<schema name="curricularCourseInquiriesRegistryDTO.submitHoursAndDays"
		type="org.fenixedu.academic.dto.inquiries.CurricularCourseInquiriesRegistryDTO" bundle="INQUIRIES_RESOURCES">
	<slot name="curricularCourse.name" key="label.curricularCourse.name" read-only="true"/>			
	<slot name="weeklyContactLoad" key="label.contactLoad.b" read-only="true">
		<property name="headerToolTip" value="toolTip.studentInquiries.weeklyScheduleLoad" />
	</slot>	
	<slot name="attendenceClassesPercentage" key="label.attendenceClassesPercentage.b1" read-only="true">
		<property name="headerToolTip" value="toolTip.studentInquiries.attendenceClassesPercentage" />
	</slot>
	<slot name="weeklyHoursSpentPercentage" key="label.weeklyHoursSpentPercentage.c" read-only="true" >
		<property name="headerToolTip" value="toolTip.studentInquiries.weeklyHoursSpentPercentage" />
	</slot>
	<slot name="studyDaysSpentInExamsSeason" key="label.studyDaysSpentInExamsSeason.d" >
		<property name="headerToolTip" value="toolTip.studentInquiries.studyDaysSpentInExamsSeason" />
	</slot>
	<slot name="courseEctsCredits" key="label.competenceCourse.ectsCredits" read-only="true"/>
	<slot name="calculatedECTSCredits" key="label.calculatedEctsCredits" read-only="true">
		<property name="headerToolTip" value="toolTip.studentInquiries.calculatedEctsCredits" />
	</slot>
</schema>

<schema name="curricularCourseInquiriesRegistryDTO.submitHoursAndDays.edit"
		type="org.fenixedu.academic.dto.inquiries.CurricularCourseInquiriesRegistryDTO" bundle="INQUIRIES_RESOURCES">
	<slot name="curricularCourse.name" key="label.curricularCourse.name" read-only="true"/>	
	<slot name="weeklyContactLoad" key="label.contactLoad" read-only="true">
		<property name="headerToolTip" value="toolTip.studentInquiries.weeklyScheduleLoad" />
	</slot>
	<slot name="attendenceClassesPercentage" key="label.attendenceClassesPercentage.withBreaks" layout="menu-select"
			validator="pt.ist.fenixWebFramework.renderers.validators.RequiredValidator">
		<property name="headerToolTip" value="toolTip.studentInquiries.attendenceClassesPercentage" />
		<property name="defaultText" value=""/>
		<property name="providerClass" value="org.fenixedu.academic.dto.inquiries.CurricularCourseInquiriesRegistryDTO$NumbersToHundred5To5" />		
	</slot>
	<slot name="weeklyHoursSpentPercentage" key="label.weeklyHoursSpentPercentage.withBreaks">
		<property name="headerToolTip" value="toolTip.studentInquiries.weeklyHoursSpentPercentage" />
		<property name="size" value="5" />
		<property name="maxLength" value="3" />	
		<validator class="pt.ist.fenixWebFramework.renderers.validators.RequiredValidator"/>
		<validator class="pt.ist.fenixWebFramework.renderers.validators.NumberValidator"/>
        <validator class="org.fenixedu.academic.ui.renderers.validators.NumberRangeValidator">
            <property name="lowerBound" value="0"/>
            <property name="upperBound" value="100"/>
        </validator>
	</slot>
	<slot name="simulatedSpentHours" key="label.calculatedAWH" read-only="true" />
	<slot name="studyDaysSpentInExamsSeason" key="label.studyDaysSpentInExamsSeason.withBreaks">
		<property name="size" value="5" />
		<property name="maxLength" value="4" />
		<property name="headerToolTip" value="toolTip.studentInquiries.studyDaysSpentInExamsSeason" />
		<validator class="pt.ist.fenixWebFramework.renderers.validators.RequiredValidator"/>
		<validator class="pt.ist.fenixWebFramework.renderers.validators.DoubleValidator"/>
        <validator class="org.fenixedu.academic.ui.renderers.validators.DoubleRangeValidator">
            <property name="lowerBound" value="0"/>
            <property name="upperBound" value="42"/>
        </validator>			
	</slot>
</schema>
</schemas>
