=== FenixEdu/fenixedu-academic/web/WEB-INF/fenix-renderers-config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
  The renderers-config element is the document root of the renderers configuration.
  
  It allows the definition and configuration of several renderers and layouts.
  -->
<!ELEMENT renderers-config (renderer)*>

<!--
  The 'renderer' element defines one renderer in the system.
  
  Each renderer must specify at least a type and a class. The type indicates
  wich type of objects the renderer supports. The class indicates the java class
  of the renderer.
  
  Additionally the layout can be specified to allow variations in the rendering
  of a certain type.
  
  The 'renderer' element also allows the inclusion of properties to configure the
  defined renderer. This way you can have two layouts for the same type, using
  the same renderer, but using different configurations.
  
  Example:
	<renderer type="java.lang.Number" class="my.package.NumberRenderer"/>

	<renderer type="java.lang.Number" layout="base-2" class="my.package.NumberRenderer">
		<property name="base" value="2"/>
	</renderer>
  
	<renderer type="java.lang.Number" layout="base-16" class="my.package.NumberRenderer">
  		<property name="base" value="16"/>
	</renderer>
	
  Renderers can be specified associated with a certain presentation mode. The default,
  and most common, are "output" and "input". If no mode is specified then it defaults
  to "output". Modes provide further distinction between renderers and allow a greater
  separation than layout. For example the "input" mode creates a surrounding input 
  context that is not necessary in the "output" mode.
  
  Example:
  	<renderer mode="output" type="java.lang.Number" class="my.package.NumberRenderer"/>
  	<renderer mode="input"  type="java.lang.Number" class="my.package.OtherNumberRenderer"/>
  	
  In the example we define a diferent renderer to present the number in the "input" mode.
  This means that when a tag is used to do the input of a number the second renderer is 
  used.
-->
<!ELEMENT renderer (property*)>

<!ATTLIST renderer
	class NMTOKEN #REQUIRED
	type NMTOKEN #REQUIRED
	layout NMTOKEN #IMPLIED
	mode NMTOKEN #IMPLIED
>

<!--
  The property element allows the configuration of the renderer specified with 'class'
  in the 'renderer' element.
  
  When the renderer is selected to render an object it will first be configured with
  the properties defined by this element.
  
  An <property name="property" value="value"/> is the same as calling 
  'setProperty(convertedValue)' in the renderer were 'convertedValue' is "value"
  converted to the property type in the renderer. Only simple property types are supported.
-->
<!ELEMENT property EMPTY>

<!ATTLIST property
	value CDATA #REQUIRED
	name CDATA #REQUIRED
>

=== FenixEdu/fenixedu-academic/metadata/fenix-renderers-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- TODO: make this a public id or at least obsolute 
     Currently there is a semi-hack built in the RendererPlugin to accept this format.
-->
<!DOCTYPE renderers-config SYSTEM "/WEB-INF/fenix-renderers-config.dtd">

<renderers-config>
<!--
  Example:
	
 	<renderer type="java.lang.Integer" layout="testing" 
			  class="net.sourceforge.fenixedu.renderers.TemplateRenderer">
		<property name="template" value="/template.jsp"/>
	</renderer>
	
    <renderer mode="input" type="java.lang.Integer"
              class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer"/>

    <renderer mode="input" type="java.lang.Integer" layout="base-16" 
              class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer">
        <property name="base" layout="16"/>
    </renderer>

	This piece means that any object of type Integer, when presented
	with the layout "testing" will be rendered by the given TemplateRenderer and
    that the renderer's property 'template' will be set to "/template.jsp". This 
    should make the rendere delegate the presentation of the number to the
    given JSP.
    
    The second part speficies that the NumberInputRenderer will be used to
    generate the input presentation of a number. If the requested layout is
    "base-16" then input format will be assumed to be in hexadecimal.
 -->
  
    <!-- ouptut -->
  
    <renderer type="java.lang.Object" class="net.sourceforge.fenixedu.renderers.StandardObjectRenderer"/>
    <renderer type="java.lang.Object" layout="tabular" class="net.sourceforge.fenixedu.renderers.StandardObjectRenderer"/>
  
    <renderer type="java.lang.Object" layout="template" class="net.sourceforge.fenixedu.renderers.TemplateRenderer"/>
    <renderer type="java.lang.Object" layout="values" class="net.sourceforge.fenixedu.renderers.ValuesRenderer"/>
    <renderer type="java.lang.Object" layout="format" class="net.sourceforge.fenixedu.renderers.FormatRenderer"/>
    
    <!-- NOTE: to be used as a layout for a slot of a DomainObject only. It's a link to the whole object details -->
    <renderer type="java.lang.Object" layout="link" class="net.sourceforge.fenixedu.presentationTier.renderers.ObjectLinkRenderer">
        <property name="destinyLayout" value="tabular"/>
    </renderer>
  
    <renderer type="java.lang.String" class="net.sourceforge.fenixedu.renderers.StringRenderer"/>
    
    <renderer type="java.lang.Number" class="net.sourceforge.fenixedu.renderers.IntegerRenderer"/>
    <renderer type="int" class="net.sourceforge.fenixedu.renderers.IntegerRenderer"/>
    <renderer type="long" class="net.sourceforge.fenixedu.renderers.IntegerRenderer"/>
    <renderer type="short" class="net.sourceforge.fenixedu.renderers.IntegerRenderer"/>
    
    <renderer type="double" class="net.sourceforge.fenixedu.renderers.NumberRenderer"/>
    <renderer type="float" class="net.sourceforge.fenixedu.renderers.NumberRenderer"/>
    
    <renderer type="java.lang.Boolean" class="net.sourceforge.fenixedu.renderers.BooleanRenderer"/>
    <renderer type="boolean" class="net.sourceforge.fenixedu.renderers.BooleanRenderer"/>
    
    <renderer type="java.lang.Enum" class="net.sourceforge.fenixedu.renderers.EnumRenderer"/>
    <renderer type="java.util.Date" class="net.sourceforge.fenixedu.renderers.DateRenderer"/>

    <renderer type="net.sourceforge.fenixedu.domain.DomainObject" class="net.sourceforge.fenixedu.presentationTier.renderers.DomainObjectLinkRenderer">
        <property name="subLayout" value="values"/>
        <property name="subSchema" value="DomainObject.oid"/>
        <property name="destinyLayout" value="tabular"/>
    </renderer>
    
    <renderer layout="nestedTemplateLayout" type="net.sourceforge.fenixedu.domain.DomainObject" class="net.sourceforge.fenixedu.renderers.TemplateRenderer">
        <property name="template" value="/departmentMember/viewDepartmentTeachersExpectations/renderers/layouts/showPersonalExpectationTemplate.jsp"/>
    </renderer>
 
    <renderer type="java.util.Collection" class="net.sourceforge.fenixedu.renderers.CollectionRenderer"/>
    <renderer type="java.util.Collection" layout="tabular" class="net.sourceforge.fenixedu.renderers.CollectionRenderer"/>
    <renderer type="java.util.Collection" layout="tabular-list" class="net.sourceforge.fenixedu.renderers.TabularListRenderer"/>
    <renderer type="java.util.Collection" layout="flowLayout" class="net.sourceforge.fenixedu.presentationTier.renderers.FlowRenderer" />

    <renderer type="java.util.List" class="net.sourceforge.fenixedu.renderers.ListRenderer"/>
    
    <!-- input -->
  
    <renderer mode="input" type="java.util.Collection" layout="tabular-sortable" class="net.sourceforge.fenixedu.renderers.OrderableCollectionRenderer"/>
    <renderer mode="input" type="java.util.Collection" layout="tabular-editable" class="net.sourceforge.fenixedu.renderers.TabularInputRenderer"/>
    <renderer mode="input" type="java.util.List" layout="option-select" class="net.sourceforge.fenixedu.presentationTier.renderers.InputCheckBoxListRenderer"/>
    <renderer mode="input" type="java.util.List" layout="external-add" class="net.sourceforge.fenixedu.renderers.ManageableListRenderer"/>

    <renderer mode="input" type="java.lang.Object" class="net.sourceforge.fenixedu.renderers.StandardInputRenderer"/>
    <renderer mode="input" type="java.lang.Object" layout="tabular" class="net.sourceforge.fenixedu.renderers.StandardInputRenderer"/>
    <renderer mode="input" type="java.lang.Object" layout="flow" class="net.sourceforge.fenixedu.renderers.FlowInputRenderer"/>

    <!--@ Can be used to fill a slot with one of many possible objects  -->
    <renderer mode="input" type="java.lang.Object" layout="menu-select" class="net.sourceforge.fenixedu.renderers.presentationTier.InputMenuOptionListRenderer"/>

    <renderer mode="input" type="java.lang.String" class="net.sourceforge.fenixedu.renderers.StringInputRenderer"/>
    <renderer mode="input" type="java.lang.String" layout="htmlEditor" class="net.sourceforge.fenixedu.presentationTier.renderers.HtmlEditorRenderer"/>
    
    <renderer mode="input" type="java.lang.Number" class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer"/>
    <renderer mode="input" type="int" class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer"/>
    <renderer mode="input" type="long" class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer"/>
    <renderer mode="input" type="short" class="net.sourceforge.fenixedu.renderers.IntegerInputRenderer"/>
    
    <renderer mode="input" type="double" class="net.sourceforge.fenixedu.renderers.FloatInputRenderer"/>
    <renderer mode="input" type="float" class="net.sourceforge.fenixedu.renderers.FloatInputRenderer"/>
	
    <renderer mode="input" type="java.lang.Boolean" class="net.sourceforge.fenixedu.renderers.BooleanInputRenderer"/>
    <renderer mode="input" type="boolean" class="net.sourceforge.fenixedu.renderers.BooleanInputRenderer"/>
    <renderer mode="input" type="java.lang.Boolean" layout="menu" class="net.sourceforge.fenixedu.renderers.BooleanMenuInputRenderer"/>
    <renderer mode="input" type="boolean" layout="menu" class="net.sourceforge.fenixedu.renderers.BooleanMenuInputRenderer"/>
    
    <renderer mode="input" type="java.lang.Enum" class="net.sourceforge.fenixedu.renderers.EnumInputRenderer"/>
    <renderer mode="input" type="java.util.Date" class="net.sourceforge.fenixedu.renderers.DateInputRenderer"/>

    <!-- NOTE: needed by the create tag. The tag selects a DomainClass but the input can proceed as with a standard domain object -->
    <renderer mode="input" type="dml.DomainClass" class="net.sourceforge.fenixedu.renderers.StandardInputRenderer"/>
    <renderer mode="input" type="dml.DomainClass" layout="tabular" class="net.sourceforge.fenixedu.renderers.StandardInputRenderer"/>

    <!-- FIXME: this should be removed, used for renderers examples only -->
    <renderer type="java.lang.Object" layout="nice-details-table" class="net.sourceforge.fenixedu.renderers.StandardObjectRenderer">
        <property name="classes" value="style1"/>
        <property name="columnClasses" value="listClasses,"/>
    </renderer>
    
    <renderer type="java.lang.Object" layout="values-dash" class="net.sourceforge.fenixedu.renderers.ValuesRenderer">
        <property name="htmlSeparator" value=" - "/>
    </renderer>
    
    <renderer mode="input" type="java.lang.String" layout="allow-case-change" class="net.sourceforge.fenixedu.renderers.StringCaseChangerRenderer"/>
</renderers-config>
